#
# MAINTAINER  troylc <wwaa1983@163.com>
# DOCKER-VERSION  1.8.3
#
# Dockerizing CentOS7: Dockerfile for building CentOS images
#
FROM centos
MAINTAINER helloWorld,troylc <wwaa1983@163.com>

ENV TZ "Asia/Shanghai"
ENV TERM xterm

# 安装openssh-server和sudo软件包，并且将sshd的UsePAM参数设置成no
RUN yum install -y openssh-server sudo curl tar vim-enhanced passwd net-tools  && \
    yum install -y java-1.8.0-openjdk && \
    yum clean all

RUN sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

# 添加测试用户admin，密码admin，并且将此用户添加到sudoers里
RUN useradd admin
RUN echo "admin:admin" | chpasswd
RUN echo "admin   ALL=(ALL)       ALL" >> /etc/sudoers
RUN echo "root:123456" | chpasswd

# 下面这两句比较特殊，在centos7上必须要有，否则创建出来的容器sshd不能登录
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key


#下面是设置tomcat的环境变量以及工作目录
ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME


# Install tomcat8
RUN cd /tmp && curl -L 'http://mirror.catn.com/pub/apache/tomcat/tomcat-8/v8.0.28/bin/apache-tomcat-8.0.28.tar.gz' | tar -xz
RUN mv /tmp/apache-tomcat-8.0.28/ /opt/tomcat8/

#下面是设置tomcat的环境变量以及工作目录
ENV CATALINA_HOME /opt/tomcat8/
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

RUN rm -rf /tmp/*

ADD tomcat.sh /etc/init.d/tomcat
RUN chmod 755 /etc/init.d/tomcat

# 启动sshd服务并且暴露22端口
RUN mkdir /var/run/sshd
EXPOSE 22

EXPOSE 8080

CMD ["catalina.sh", "run"]
# 设置tomcat初始化运行，SSH终端服务作为后台运行