#
# MAINTAINER        Carson,C.J.Zeong <zcy@nicescale.com>
# DOCKER-VERSION    1.8.3
#
# Dockerizing CentOS7: Dockerfile for building CentOS images
#
FROM       nginx
MAINTAINER helloWorld,troylc <wwaa1983@163.com>

ENV TZ "Asia/Shanghai"
ENV TERM xterm

RUN apt-get update && \
	apt-get install -y curl wget vim passwd sudo hostname net-tools rsync man



